### ISSUE TITLE
Incompatible versioning scheme

### ISSUE THREAD

**Issue by ripienaar** [42atomys/sprout#7]
I would love to use this project but your versioning scheme is not compatible with go mod.  Valid versions need to be v1.2.3 not v1.2. 

This result in go reporting version usage like this:

```diff
-       github.com/Masterminds/sprig/v3 v3.2.3
+       github.com/42atomys/sprout v0.0.0-20240403003052-d64a48ef7bae
```

Please tag a correct release like `v0.2.0`

**Comment by ripienaar** [comment]
It might also be worth putting this in a dedicated organization to avoid the inevitable nightmare when this repo gets renamed later.

**Comment by andig** [comment]
go get github.com/42atomys/sprout@latest

seems to get master, not 0.2.

**Comment by ripienaar** [comment]
Yes because it doesn’t consider the releases as valid.

**Comment by andig** [comment]
@42atomys Having a stable versioning scheme is important for _not_ relying on master. It should be possible to add another tag to the broken release.

**Comment by 42atomys** [comment]
HI, oh really strange ! I will check to fix that asap

**Comment by 42atomys** [comment]
That's will be fixed in 30 minutes ~, the tag was pushed after invoking go get once, which poisoned the Go module proxy cache 😢 

From https://proxy.golang.org/:

> if someone requested the version before the tag was pushed, it may take up to 30 minutes for the mirror's cache to expire and fresh data about the version to become available.

> [!NOTE]
> I will continue to check until the cache has refreshed on https://proxy.golang.org/github.com/42atomys/sprout/@v/v0.2.0.info and will close the issue once the version appears!

Sorry about this mistake 🙏. Thanks for using the project from the beginning !

**Comment by 42atomys** [comment]
This is fixed ✅ 
The error handling will be release soon 🚀
