### ISSUE TITLE
Proposal: add toDuration

### ISSUE THREAD

**Issue by andig** [42atomys/sprout#8]
See https://github.com/Masterminds/sprig/issues/388

**Comment by 42atomys** [comment]
Hi @andig thanks for your interest again. This is already scheduled for the v1 🍕 🎉 

(a complete list can be found on https://docs.atom.codes/sprout/roadmap-to-sprout-v1.0 at the bottom of the page, and toDuration are in it)

I will create a GitHub project with all to do item to have a cleaner vision until the v1 🌱

**Comment by 42atomys** [comment]
Hello @andig,

Thank you for your patience! 🕐 The function has been successfully implemented and will be included in the upcoming release, version `v0.3` 🚀 

We appreciate your support and look forward to your feedback on the new features!
